start scripts\build_xaa.bat
start scripts\build_xab.bat
start scripts\build_xac.bat
start scripts\build_xad.bat
start scripts\build_xae.bat
start scripts\build_xaf.bat
start scripts\build_xag.bat
start scripts\build_xah.bat
start scripts\build_xai.bat
start scripts\build_xaj.bat
start scripts\build_xak.bat
start scripts\build_xal.bat